"""
CATALOGO DE HALLAZGOS Y BASE DE PATOLOGIAS.

POR QUE UNA LISTA CERRADA Y NO TEXTO LIBRE

Podria dejarse escribir "le duele mucho la cabeza de repente" y que la app
lo interpretara. Es mas comodo de teclear, y es una mala idea: cada
interpretacion es una ocasion de equivocarse en silencio. Si el motor
entiende mal un dato, no avisa de nada -simplemente ordena mal el
diferencial, y el alumno aprende algo falso sin enterarse-.

Con una lista cerrada, el hallazgo que se elige es EXACTAMENTE el mismo
identificador que aparece en la ficha de la patologia. No hay nada que
adivinar y el descarte es fiable. La comodidad se recupera con un buscador
encima de la lista, que es un problema de pantalla y no de fiabilidad.

SOBRE ESTA BASE

El catalogo de hallazgos de abajo es la version de arranque, orientada a los
tres sistemas con los que empieza la app: neurologia, oncohematologia e
infecciosas. Se amplia añadiendo entradas; no hay que tocar el motor.

La base va creciendo por tandas: se genera con una IA potente en el formato
de arriba y se REVISA una por una antes de entrar. En la primera tanda hubo
que corregir un patron peligroso -marcar la fiebre como INCOMPATIBLE en
enfermedades cronicas como el Parkinson o el Alzheimer-, que habria hecho
desaparecer esos diagnosticos del diferencial de cualquier paciente con
febricula. Un descarte duro solo vale cuando de verdad es excluyente.

Los tres sistemas del arranque -neurologia, infecciosas y oncohematologia-
estan ya cubiertos a un nivel razonable. Ampliar es añadir fichas: el motor
no se toca.

Ninguna ficha entra sin repasarla: aqui un error no da un fallo visible,
da una respuesta segura y equivocada.
"""
from __future__ import annotations

SISTEMAS = {
    "neuro": "Neurología",
    "infecciosas": "Infecciosas",
    "oncohemato": "Oncohematología",
}

# ---------------------------------------------------------------------------
# CATALOGO DE HALLAZGOS
# ---------------------------------------------------------------------------
# Agrupado en bloques porque una lista de noventa cosas seguidas no hay quien
# la use en un movil. El buscador de la pantalla filtra sobre el nombre.

HALLAZGOS: list[dict] = []

# COSTE de averiguar cada cosa. No es dinero: es lo que le cuesta al paciente
# y al sistema. Preguntar si tiene fiebre es gratis; una puncion lumbar no.
#
# Sirve para que la app no sugiera empezar la casa por el tejado. Sin esto
# proponia "mira el LCR" como primera pregunta ante una cefalea, que
# discrimina muchisimo pero es exactamente lo que un medico NO hace primero.
COSTES = {
    "Generales": 1,
    "Curso": 1,
    "Neurológicos": 1,
    "Infecciosos": 1,
    "Antecedentes y riesgo": 1,
    "Exploración": 2,
    "Analítica": 4,
    "Hemograma": 4,
    "Coagulación": 4,
    "Bioquímica": 4,
    "Electrocardiograma": 3,
    "Microbiología": 5,
    "Otros aparatos": 2,
    "Imagen": 6,
    "Líquido cefalorraquídeo": 8,
}


def _bloque(bloque: str, items: dict[str, str]) -> None:
    for hid, nombre in items.items():
        HALLAZGOS.append({"id": hid, "nombre": nombre, "bloque": bloque,
                          "coste": COSTES.get(bloque, 1)})


_bloque("Generales", {
    "fiebre": "Fiebre (>38 ºC)",
    "febricula": "Febrícula",
    "perdida_peso": "Pérdida de peso involuntaria",
    "sudoracion_nocturna": "Sudoración nocturna",
    "astenia": "Astenia",
    "anorexia": "Anorexia",
    "malestar_general": "Malestar general",
    "prurito": "Prurito generalizado",
    "escalofrios": "Escalofríos",
    "fiebre_prolongada": "Fiebre prolongada (más de 2 semanas)",
    "ictericia": "Ictericia",
    "mialgias": "Mialgias",
    "artralgias": "Artralgias",
})

_bloque("Curso", {
    "instauracion_subita": "Instauración súbita (segundos)",
    "instauracion_horas": "Instauración en horas",
    "instauracion_dias": "Instauración en días",
    "instauracion_semanas": "Instauración en semanas o meses",
    "curso_recurrente": "Episodios recurrentes previos",
    "curso_progresivo": "Curso progresivo sin mejoría",
})

_bloque("Neurológicos", {
    "cefalea_brusca": "Cefalea de inicio brusco (en trueno)",
    "cefalea_progresiva": "Cefalea progresiva",
    "cefalea_matutina": "Cefalea matutina que despierta",
    "rigidez_nuca": "Rigidez de nuca",
    "signos_meningeos": "Signos meníngeos (Kernig / Brudzinski)",
    "fotofobia": "Fotofobia",
    "vomitos_proyectivos": "Vómitos en escopetazo",
    "alteracion_conciencia": "Alteración del nivel de conciencia",
    "confusion": "Confusión / desorientación",
    "focalidad_motora": "Focalidad motora",
    "deficit_sensitivo": "Déficit sensitivo",
    "afasia": "Afasia",
    "crisis_convulsiva": "Crisis convulsiva",
    "diplopia": "Diplopía",
    "ataxia": "Ataxia",
    "papiledema": "Papiledema",
    "aura_visual": "Aura visual previa",
    "alteracion_conducta": "Alteración de la conducta o del comportamiento",
    "asterixis": "Asterixis (flapping)",
    "ptosis_palpebral": "Ptosis palpebral",
    "disfagia": "Disfagia",
    "fatigabilidad_muscular": "Fatigabilidad muscular con el esfuerzo",
    "debilidad_simetrica_ascendente": "Debilidad simétrica ascendente",
    "arreflexia": "Arreflexia",
    "parestesias_distales": "Parestesias distales",
    "temblor_reposo": "Temblor de reposo",
    "rigidez_muscular": "Rigidez muscular",
    "bradicinesia": "Bradicinesia",
    "inestabilidad_postural": "Inestabilidad postural",
    "micrografia": "Micrografía",
    "hipofonia": "Hipofonía",
    "anosmia": "Anosmia",
    "deterioro_memoria_episodica": "Deterioro de la memoria episódica",
    "desorientacion_temporoespacial": "Desorientación temporoespacial",
    "afasia_anomica": "Afasia anómica",
    "apraxia": "Apraxia",
    "agnosia": "Agnosia",
    "neuropatia_periferica": "Neuropatía periférica",
    "atencion_fluctuante": "Atención fluctuante",
    "inversion_ciclo_sueno": "Inversión del ciclo sueño-vigilia",
    "alucinaciones_visuales": "Alucinaciones visuales",
    "fluctuacion_cognitiva": "Fluctuación cognitiva",
    "trastorno_conducta_rem": "Trastorno de conducta del sueño REM",
    "sensibilidad_neurolepticos": "Sensibilidad a los neurolépticos",
    "desinhibicion_social": "Desinhibición social",
    "apatia": "Apatía",
    "perdida_empatia": "Pérdida de empatía",
    "conducta_compulsiva": "Conducta compulsiva o ritualista",
    "hiperoralidad": "Hiperoralidad o cambio de hábitos alimentarios",
    "afasia_no_fluyente": "Afasia progresiva no fluente",
    "deterioro_cognitivo_ejecutivo": "Deterioro cognitivo de perfil ejecutivo",
    "marcha_apraxica": "Marcha apráxica (imantada)",
    "marcha_espastica": "Marcha espástica",
    "oftalmoplejia_supranuclear": "Oftalmoplejía supranuclear vertical",
    "oftalmoplejia": "Oftalmoplejía",
    "nistagmo": "Nistagmo",
    "nistagmo_posicional": "Nistagmo posicional",
    "caidas_precoces": "Caídas precoces y de repetición",
    "rigidez_axial": "Rigidez axial",
    "respuesta_levodopa": "Respuesta clara a la levodopa",
    "debilidad_progresiva_asimetrica": "Debilidad progresiva asimétrica",
    "fasciculaciones": "Fasciculaciones",
    "hiperreflexia": "Hiperreflexia",
    "signo_babinski": "Signo de Babinski",
    "atrofia_muscular": "Atrofia muscular",
    "torpeza_manual": "Torpeza manual",
    "nivel_sensitivo": "Nivel sensitivo",
    "lhermitte": "Signo de Lhermitte",
    "hipoestesia_distal": "Hipoestesia en calcetín y guante",
    "dolor_quemazon_nocturno": "Dolor urente de predominio nocturno",
    "amnesia_antegrada": "Amnesia anterógrada",
    "disartria": "Disartria",
    "vertigo_posicional": "Vértigo de giro breve con los cambios de postura",
    "dix_hallpike_positivo": "Maniobra de Dix-Hallpike positiva",
    "acufenos": "Acúfenos",
    "hipoacusia": "Hipoacusia",
    "perdida_vision_unilateral": "Pérdida de visión monocular",
    "dolor_ocular_movimiento": "Dolor ocular con los movimientos",
    "discromatopsia": "Discromatopsia",
    "deficit_pupilar_aferente": "Defecto pupilar aferente relativo",
    "claudicacion_mandibular": "Claudicación mandibular",
    "cefalea_localizada_nueva": "Cefalea nueva localizada en la sien",
    "dolor_lumbar_irradiado": "Dolor lumbar irradiado por la pierna",
    "lassegue_positivo": "Lasègue positivo",
    "deficit_motor_radicular": "Déficit motor de distribución radicular",
    "valsalva_agrava": "Empeora con la tos o el esfuerzo",
    "anestesia_silla_montar": "Anestesia en silla de montar",
    "incontinencia_urinaria": "Incontinencia urinaria",
    "sincope": "Síncope",
})

_bloque("Infecciosos", {
    "odinofagia": "Odinofagia",
    "tos": "Tos",
    "expectoracion": "Expectoración purulenta",
    "disnea": "Disnea",
    "dolor_pleuritico": "Dolor pleurítico",
    "diarrea": "Diarrea",
    "disuria": "Disuria / síndrome miccional",
    "exantema": "Exantema",
    "petequias": "Petequias / púrpura",
    "foco_orl": "Foco ORL (otitis, sinusitis)",
    "viaje_reciente": "Viaje reciente a zona endémica",
    "contacto_epidemico": "Contacto epidemiológico conocido",
    "hemoptisis": "Hemoptisis",
})

_bloque("Exploración", {
    "adenopatias_dolorosas": "Adenopatías dolorosas",
    "adenopatias_indoloras": "Adenopatías indoloras y duras",
    "adenopatias_generalizadas": "Adenopatías generalizadas",
    "esplenomegalia": "Esplenomegalia",
    "hepatomegalia": "Hepatomegalia",
    "palidez": "Palidez mucocutánea",
    "equimosis": "Equimosis / hematomas espontáneos",
    "sangrado_mucosas": "Sangrado de mucosas (gingivorragia, epistaxis)",
    "dolor_oseo": "Dolor óseo",
    "masa_palpable": "Masa palpable",
    "hipertrofia_gingival": "Hipertrofia gingival",
    "masa_extranodal": "Masa extranodal",
    "fracturas_patologicas": "Fracturas patológicas",
    "candidiasis_oral": "Candidiasis oral (muguet)",
    "alopecia_parcheada": "Alopecia parcheada",
    "tumefaccion_articular": "Tumefacción articular",
    "hemartros": "Hemartros (sangre en la articulación)",
    "eritema_local": "Eritema local",
})

_bloque("Analítica", {
    "leucocitosis": "Leucocitosis",
    "leucopenia": "Leucopenia",
    "neutrofilia": "Neutrofilia",
    "linfocitosis": "Linfocitosis con linfocitos atípicos",
    "anemia": "Anemia",
    "trombopenia": "Trombopenia",
    "pancitopenia": "Pancitopenia",
    "blastos_sangre": "Blastos en sangre periférica",
    "vsg_elevada": "VSG elevada",
    "pcr_elevada": "PCR elevada",
    "procalcitonina_elevada": "Procalcitonina elevada",
    "ldh_elevada": "LDH elevada",
    "hipercalcemia": "Hipercalcemia",
    "acido_urico_elevado": "Ácido úrico elevado",
    "amoniaco_elevado": "Amonio elevado",
    "tp_alargado": "Tiempo de protrombina alargado",
    "albumina_baja": "Albúmina baja",
    "insuficiencia_renal": "Insuficiencia renal",
    "proteina_monoclonal": "Proteína monoclonal en suero u orina",
    "cadenas_ligeras_libres": "Cadenas ligeras libres elevadas",
    "linfocitosis_absoluta": "Linfocitosis absoluta mantenida",
    "transaminasas_elevadas": "Transaminasas elevadas",
    "neutropenia": "Neutropenia",
    "basofilia": "Basofilia",
    "eritrocitosis": "Eritrocitosis (hematocrito elevado)",
    "trombocitosis": "Trombocitosis",
    "macrocitosis": "Macrocitosis (VCM elevado)",
    "esquistocitos": "Esquistocitos en el frotis",
    "leucoeritroblastosis": "Leucoeritroblastosis",
    "dacriocitos": "Dacriocitos (hematíes en lágrima)",
    "displasia_medular": "Displasia en la médula ósea",
    "hipofibrinogenemia": "Fibrinógeno bajo",
    "hiperpotasemia": "Hiperpotasemia",
    "hiperfosfatemia": "Hiperfosfatemia",
    "hipocalcemia": "Hipocalcemia",
    "acidosis_metabolica": "Acidosis metabólica",
    "rabdomiolisis": "Rabdomiólisis (CK muy elevada)",
    "ttpa_prolongado": "TTPA prolongado",
    "dimero_d_elevado": "Dímero D elevado",
})

_bloque("Líquido cefalorraquídeo", {
    "lcr_purulento": "LCR de aspecto turbio o purulento",
    "lcr_claro": "LCR claro",
    "lcr_pleocitosis_pmn": "LCR con pleocitosis de polimorfonucleares",
    "lcr_pleocitosis_linfo": "LCR con pleocitosis linfocitaria",
    "lcr_hipoglucorraquia": "LCR con glucosa baja",
    "lcr_proteinorraquia": "LCR con proteínas elevadas",
    "lcr_hematico": "LCR hemático / xantocrómico",
    "lcr_normal": "LCR normal",
    "lcr_albuminocitologica": "LCR con disociación albuminocitológica",
})

_bloque("Imagen", {
    "tc_normal": "TC craneal normal",
    "tc_hemorragia_subaracnoidea": "TC con sangre en espacio subaracnoideo",
    "tc_lesion_ocupante": "TC/RM con lesión ocupante de espacio",
    "rm_temporal": "RM con afectación de lóbulos temporales",
    "rx_condensacion": "Radiografía con condensación pulmonar",
    "masa_mediastinica": "Masa mediastínica",
    "rx_cavitacion_apical": "Radiografía con cavitación apical",
    "atrofia_hipocampal": "RM con atrofia hipocampal",
    "lesiones_liticas": "Lesiones líticas óseas",
    "ecocardiograma_vegetaciones": "Ecocardiograma con vegetaciones",
    "ventriculomegalia": "Ventriculomegalia desproporcionada",
    "rm_nervio_optico": "RM con realce del nervio óptico",
})

_bloque("Antecedentes y riesgo", {
    "inmunodepresion": "Inmunodepresión",
    "vih": "Infección por VIH",
    "esplenectomia": "Esplenectomía previa",
    "quimioterapia_previa": "Quimioterapia o radioterapia previa",
    "antecedente_familiar_onco": "Antecedentes familiares oncológicos",
    "tabaquismo": "Tabaquismo",
    "advp": "Uso de drogas por vía parenteral",
    "sindrome_down": "Síndrome de Down",
    "anticoagulacion": "Tratamiento anticoagulante",
    "infecciones_recurrentes": "Infecciones de repetición",
    "alcoholismo_cronico": "Alcoholismo crónico",
    "antecedente_epilepsia": "Epilepsia conocida",
    "puerperio": "Embarazo o puerperio",
    "diabetes": "Diabetes mellitus",
    "antecedente_familiar_sangrado": "Antecedentes familiares de sangrado",
})

_bloque("Otros aparatos", {
    "ascitis": "Ascitis",
    "estrenimiento": "Estreñimiento",
    "dolor_suprapubico": "Dolor suprapúbico",
    "dolor_lumbar": "Dolor lumbar / puñopercusión positiva",
    "taquicardia": "Taquicardia",
    "hipotension": "Hipotensión",
    "soplo_cardiaco_nuevo": "Soplo cardiaco nuevo",
    "fenomenos_embolicos": "Fenómenos embólicos periféricos",
    "nodos_osler": "Nódulos de Osler",
    "manchas_janeway": "Manchas de Janeway",
    "dolor_abdominal": "Dolor abdominal",
    "nauseas_vomitos": "Náuseas y vómitos",
    "hipertension": "Hipertensión arterial",
    "hiperviscosidad": "Síndrome de hiperviscosidad",
    "eritromelalgia": "Eritromelalgia",
    "dolor_cervical": "Dolor cervical",
    "ulceras_plantares": "Úlceras plantares",
    "artropatia_charcot": "Artropatía de Charcot",
})

_bloque("Electrocardiograma", {
    "ritmo_sinusal": "Ritmo sinusal",
    "fibrilacion_auricular": "Fibrilación auricular",
    "flutter_auricular": "Flutter auricular",
    "taquicardia_ventricular": "Taquicardia ventricular",
    "extrasistoles_ventriculares": "Extrasístoles ventriculares",
    "bradicardia": "Bradicardia",
    "bloqueo_av": "Bloqueo auriculoventricular",
    "bloqueo_rama_izquierda": "Bloqueo de rama izquierda",
    "bloqueo_rama_derecha": "Bloqueo de rama derecha",
    "elevacion_st": "Elevación del ST",
    "descenso_st": "Descenso del ST",
    "ondas_t_negativas": "Ondas T negativas",
    "ondas_t_picudas": "Ondas T picudas",
    "ondas_q_patologicas": "Ondas Q patológicas",
    "qt_largo": "QT largo",
    "bajo_voltaje": "Bajo voltaje generalizado",
    "hipertrofia_ventricular": "Hipertrofia ventricular izquierda",
    "patron_s1q3t3": "Patrón S1Q3T3",
    "elevacion_st_difusa": "Elevación del ST difusa con descenso del PR",
    "ecg_normal": "Electrocardiograma normal",
})

_bloque("Microbiología", {
    "hemocultivos_positivos": "Hemocultivos positivos",
    "urocultivo_positivo": "Urocultivo positivo",
})

# ---------------------------------------------------------------------------
# LA ANALITICA, POR PARTES
# ---------------------------------------------------------------------------
# Un solo cajon de "Analitica" con cuarenta cosas dentro no se maneja: quien
# esta mirando un hemograma no quiere ir tropezando con iones y enzimas. Se
# parte en las tres familias en que de verdad se piden y se leen.
#
# Se hace aqui, reasignando, en vez de reescribir las listas de arriba:
# menos ocasiones de equivocarse moviendo lineas de sitio.
_REPARTO_ANALITICA = {
    "Hemograma": [
        "leucocitosis", "leucopenia", "neutrofilia", "neutropenia", "linfocitosis",
        "linfocitosis_absoluta", "basofilia", "anemia", "macrocitosis", "eritrocitosis",
        "trombopenia", "trombocitosis", "pancitopenia", "blastos_sangre",
        "esquistocitos", "leucoeritroblastosis", "dacriocitos", "displasia_medular",
    ],
    "Coagulación": ["tp_alargado", "hipofibrinogenemia",
                    "ttpa_prolongado", "dimero_d_elevado"],
}
for _grupo, _ids in _REPARTO_ANALITICA.items():
    for _h in HALLAZGOS:
        if _h["id"] in _ids:
            _h["bloque"] = _grupo
for _h in HALLAZGOS:
    if _h["bloque"] == "Analítica":
        _h["bloque"] = "Bioquímica"

# ---------------------------------------------------------------------------
# PESTAÑAS
# ---------------------------------------------------------------------------
# Los bloques son demasiados para una sola columna en un movil. Se agrupan
# en las pestañas con las que se piensa de verdad en la practica: primero lo
# que ves y preguntas, y solo despues lo que pides.
#
# El orden importa: la pestaña de clinica va primera porque es por donde se
# empieza, y las pruebas caras van al final por el mismo motivo por el que
# el sugeridor no las propone antes de tiempo.
PESTANAS = [
    ("clinica", "Clínica", ["Generales", "Curso", "Neurológicos", "Infecciosos",
                            "Otros aparatos", "Exploración", "Antecedentes y riesgo"]),
    ("hemograma", "Hemograma", ["Hemograma"]),
    ("coagulacion", "Coagulación", ["Coagulación"]),
    ("bioquimica", "Bioquímica", ["Bioquímica"]),
    ("cultivos", "Cultivos", ["Microbiología"]),
    ("imagen", "Imagen", ["Imagen"]),
    ("ecg", "ECG", ["Electrocardiograma"]),
    ("especiales", "Pruebas especiales", ["Líquido cefalorraquídeo"]),
    # No agrupa bloques del catalogo: es la pantalla donde se escribe la
    # cifra exacta y el codigo dice si esta alta o baja.
    ("valores", "Valores exactos", []),
]

_PESTANA_DE_BLOQUE = {b: clave for clave, _, bs in PESTANAS for b in bs}
for _h in HALLAZGOS:
    _h["pestana"] = _PESTANA_DE_BLOQUE.get(_h["bloque"], "clinica")

HALLAZGOS_POR_ID = {h["id"]: h for h in HALLAZGOS}


def bloques() -> list[dict]:
    """El catalogo agrupado, tal y como lo necesita la pantalla."""
    orden: list[str] = []
    grupos: dict[str, list[dict]] = {}
    for h in HALLAZGOS:
        if h["bloque"] not in grupos:
            grupos[h["bloque"]] = []
            orden.append(h["bloque"])
        grupos[h["bloque"]].append({"id": h["id"], "nombre": h["nombre"]})
    return [{"bloque": b, "pestana": _PESTANA_DE_BLOQUE.get(b, "clinica"),
             "hallazgos": grupos[b]} for b in orden]


def pestanas() -> list[dict]:
    """Las pestañas con lo que lleva cada una, para pintarlas en orden."""
    from app.api import clinica_valores
    salida = []
    for clave, titulo, bs in PESTANAS:
        cuantos = (len(clinica_valores.ANALITOS) if clave == "valores"
                   else sum(1 for h in HALLAZGOS if h["pestana"] == clave))
        salida.append({"clave": clave, "titulo": titulo, "bloques": bs,
                       "cuantos": cuantos})
    return salida


def catalogo_plano() -> str:
    """El catalogo entero como texto, para pasarselo a la IA.

    Va como `identificador = nombre` y agrupado, que es como mejor lo
    respetan los modelos: si les das solo los nombres bonitos, devuelven
    nombres bonitos y luego no encajan con nada.
    """
    lineas = []
    for b in bloques():
        lineas.append(f"[{b['bloque']}]")
        lineas += [f"{h['id']} = {h['nombre']}" for h in b["hallazgos"]]
    return "\n".join(lineas)


# ---------------------------------------------------------------------------
# PATOLOGIAS
# ---------------------------------------------------------------------------
# PROVISIONAL. Estas fichas existen para comprobar que el motor descarta y
# ordena como debe. No estan revisadas para estudiar con ellas.
#
# Formato de cada ficha:
#   id, nombre, sistemas, edad_tipica [min, max], sexo, genetica
#   hallazgos: {id_hallazgo: tipico | frecuente | posible | atipico | incompatible}
#
# Los campos explicativos (por que da esta clinica, por que se pide esta
# prueba, que esperamos ver, tratamiento y que esperamos de el, efectos
# secundarios) NO van aqui: se generan una vez con IA sobre esta ficha como
# referencia y se guardan. Ver seccion 6 del proyecto.

PATOLOGIAS: list[dict] = [
    {
        "id": "meningitis_bacteriana",
        "nombre": "Meningitis bacteriana aguda",
        "sistemas": ["infecciosas", "neuro"],
        "edad_tipica": [0, 90],
        "sexo": None,
        "genetica": "Déficit de complemento y asplenia predisponen a meningococo.",
        "hallazgos": {
            "fiebre": "tipico",
            "rigidez_nuca": "tipico",
            "signos_meningeos": "tipico",
            "cefalea_progresiva": "frecuente",
            "instauracion_horas": "tipico",
            "alteracion_conciencia": "frecuente",
            "fotofobia": "frecuente",
            "vomitos_proyectivos": "frecuente",
            "petequias": "posible",
            "leucocitosis": "frecuente",
            "neutrofilia": "frecuente",
            "pcr_elevada": "frecuente",
            "procalcitonina_elevada": "tipico",
            "lcr_purulento": "tipico",
            "lcr_pleocitosis_pmn": "tipico",
            "lcr_hipoglucorraquia": "tipico",
            "lcr_proteinorraquia": "frecuente",
            "esplenectomia": "posible",
            "foco_orl": "posible",
            "instauracion_semanas": "atipico",
            "lcr_normal": "incompatible",
        },
    },
    {
        "id": "meningitis_virica",
        "nombre": "Meningitis vírica",
        "sistemas": ["infecciosas", "neuro"],
        "edad_tipica": [5, 40],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre": "frecuente",
            "cefalea_progresiva": "tipico",
            "rigidez_nuca": "frecuente",
            "fotofobia": "frecuente",
            "instauracion_dias": "frecuente",
            "instauracion_horas": "posible",
            "malestar_general": "frecuente",
            "lcr_claro": "tipico",
            "lcr_pleocitosis_linfo": "tipico",
            "lcr_proteinorraquia": "posible",
            "lcr_hipoglucorraquia": "atipico",
            "lcr_pleocitosis_pmn": "atipico",
            "alteracion_conciencia": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "encefalitis_herpetica",
        "nombre": "Encefalitis herpética",
        "sistemas": ["infecciosas", "neuro"],
        "edad_tipica": [0, 90],
        "sexo": None,
        "genetica": "Descritos déficits raros de la vía TLR3.",
        "hallazgos": {
            "fiebre": "tipico",
            "alteracion_conducta": "tipico",
            "confusion": "tipico",
            "crisis_convulsiva": "frecuente",
            "afasia": "frecuente",
            "instauracion_dias": "tipico",
            "cefalea_progresiva": "frecuente",
            "alteracion_conciencia": "frecuente",
            "rm_temporal": "tipico",
            "lcr_pleocitosis_linfo": "frecuente",
            "lcr_hematico": "posible",
            "lcr_claro": "frecuente",
            "instauracion_subita": "atipico",
        },
    },
    {
        "id": "hemorragia_subaracnoidea",
        "nombre": "Hemorragia subaracnoidea",
        "sistemas": ["neuro"],
        "edad_tipica": [40, 70],
        "sexo": "predomina_mujer",
        "genetica": "Poliquistosis renal y Ehlers-Danlos; agregación familiar de aneurismas.",
        "hallazgos": {
            "cefalea_brusca": "tipico",
            "instauracion_subita": "tipico",
            "vomitos_proyectivos": "frecuente",
            "rigidez_nuca": "frecuente",
            "alteracion_conciencia": "frecuente",
            "fotofobia": "posible",
            "tc_hemorragia_subaracnoidea": "tipico",
            "lcr_hematico": "tipico",
            "focalidad_motora": "posible",
            "anticoagulacion": "posible",
            "fiebre": "atipico",
            "instauracion_semanas": "atipico",
        },
    },
    {
        "id": "migrana",
        "nombre": "Migraña",
        "sistemas": ["neuro"],
        "edad_tipica": [15, 45],
        "sexo": "predomina_mujer",
        "genetica": "Fuerte agregación familiar; migraña hemipléjica familiar (CACNA1A, ATP1A2, SCN1A).",
        "hallazgos": {
            "cefalea_progresiva": "tipico",
            "curso_recurrente": "tipico",
            "fotofobia": "tipico",
            "aura_visual": "frecuente",
            "vomitos_proyectivos": "posible",
            "instauracion_horas": "frecuente",
            "fiebre": "incompatible",
            "rigidez_nuca": "incompatible",
            "papiledema": "incompatible",
            "alteracion_conciencia": "atipico",
            "crisis_convulsiva": "atipico",
        },
    },
    {
        "id": "tumor_cerebral",
        "nombre": "Tumor cerebral primario",
        "sistemas": ["neuro", "oncohemato"],
        "edad_tipica": [45, 75],
        "sexo": None,
        "genetica": "Li-Fraumeni, neurofibromatosis, Turcot; la mayoría son esporádicos.",
        "hallazgos": {
            "cefalea_matutina": "tipico",
            "cefalea_progresiva": "tipico",
            "instauracion_semanas": "tipico",
            "curso_progresivo": "tipico",
            "papiledema": "frecuente",
            "crisis_convulsiva": "frecuente",
            "focalidad_motora": "frecuente",
            "vomitos_proyectivos": "frecuente",
            "alteracion_conducta": "posible",
            "tc_lesion_ocupante": "tipico",
            "instauracion_subita": "atipico",
            "fiebre": "atipico",
        },
    },
    {
        "id": "lma",
        "nombre": "Leucemia mieloide aguda",
        "sistemas": ["oncohemato"],
        "edad_tipica": [60, 85],
        "sexo": None,
        "genetica": "t(15;17) en la promielocítica, t(8;21), inv(16); riesgo aumentado en síndrome de Down.",
        "hallazgos": {
            "astenia": "tipico",
            "palidez": "tipico",
            "anemia": "tipico",
            "trombopenia": "tipico",
            "blastos_sangre": "tipico",
            "equimosis": "frecuente",
            "sangrado_mucosas": "frecuente",
            "fiebre": "frecuente",
            "pancitopenia": "frecuente",
            "instauracion_semanas": "frecuente",
            "hipertrofia_gingival": "posible",
            "leucocitosis": "posible",
            "ldh_elevada": "frecuente",
            "acido_urico_elevado": "frecuente",
            "quimioterapia_previa": "posible",
            "sindrome_down": "posible",
            "curso_recurrente": "atipico",
        },
    },
    {
        "id": "lla",
        "nombre": "Leucemia linfoblástica aguda",
        "sistemas": ["oncohemato"],
        "edad_tipica": [2, 10],
        "sexo": "predomina_varon",
        "genetica": "Cromosoma Philadelphia t(9;22) de mal pronóstico; síndrome de Down.",
        "hallazgos": {
            "astenia": "tipico",
            "palidez": "tipico",
            "anemia": "tipico",
            "trombopenia": "tipico",
            "blastos_sangre": "tipico",
            "dolor_oseo": "frecuente",
            "adenopatias_generalizadas": "frecuente",
            "hepatomegalia": "frecuente",
            "esplenomegalia": "frecuente",
            "fiebre": "frecuente",
            "equimosis": "frecuente",
            "masa_mediastinica": "posible",
            "sindrome_down": "posible",
            "ldh_elevada": "frecuente",
        },
    },
    {
        "id": "linfoma_hodgkin",
        "nombre": "Linfoma de Hodgkin",
        "sistemas": ["oncohemato"],
        "edad_tipica": [18, 35],
        "sexo": None,
        "genetica": "Asociación con VEB; agregación familiar leve.",
        "hallazgos": {
            "adenopatias_indoloras": "tipico",
            "adenopatias_generalizadas": "frecuente",
            "sudoracion_nocturna": "tipico",
            "perdida_peso": "tipico",
            "febricula": "frecuente",
            "prurito": "frecuente",
            "instauracion_semanas": "tipico",
            "masa_mediastinica": "frecuente",
            "vsg_elevada": "frecuente",
            "ldh_elevada": "posible",
            "esplenomegalia": "posible",
            "astenia": "frecuente",
            "instauracion_subita": "atipico",
            "adenopatias_dolorosas": "atipico",
        },
    },
    {
        "id": "mononucleosis",
        "nombre": "Mononucleosis infecciosa",
        "sistemas": ["infecciosas"],
        "edad_tipica": [15, 25],
        "sexo": None,
        "genetica": "Síndrome linfoproliferativo ligado al X en formas graves.",
        "hallazgos": {
            "odinofagia": "tipico",
            "adenopatias_dolorosas": "tipico",
            "fiebre": "tipico",
            "astenia": "tipico",
            "esplenomegalia": "frecuente",
            "linfocitosis": "tipico",
            "hepatomegalia": "posible",
            "exantema": "posible",
            "malestar_general": "frecuente",
            "instauracion_dias": "frecuente",
            "instauracion_semanas": "posible",
            "blastos_sangre": "incompatible",
        },
    },
    {
        "id": "tuberculosis_pulmonar",
        "nombre": "Tuberculosis pulmonar",
        "sistemas": ["infecciosas"],
        "edad_tipica": [20, 60],
        "sexo": None,
        "genetica": "Polimorfismos de susceptibilidad descritos; sin herencia mendeliana.",
        "hallazgos": {
            "tos": "tipico",
            "instauracion_semanas": "tipico",
            "sudoracion_nocturna": "tipico",
            "perdida_peso": "tipico",
            "febricula": "frecuente",
            "hemoptisis": "frecuente",
            "expectoracion": "frecuente",
            "rx_cavitacion_apical": "tipico",
            "astenia": "frecuente",
            "vih": "posible",
            "contacto_epidemico": "frecuente",
            "advp": "posible",
            "vsg_elevada": "frecuente",
            "instauracion_subita": "atipico",
        },
    },
    {
        "id": "neumonia_adquirida",
        "nombre": "Neumonía adquirida en la comunidad",
        "sistemas": ["infecciosas"],
        "edad_tipica": [0, 90],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre": "tipico",
            "tos": "tipico",
            "expectoracion": "frecuente",
            "disnea": "frecuente",
            "dolor_pleuritico": "frecuente",
            "instauracion_dias": "tipico",
            "rx_condensacion": "tipico",
            "leucocitosis": "frecuente",
            "neutrofilia": "frecuente",
            "pcr_elevada": "frecuente",
            "procalcitonina_elevada": "frecuente",
            "confusion": "posible",
            "tabaquismo": "posible",
            "instauracion_semanas": "atipico",
        },
    },
    {
        "id": "accidente_isquemico_transitorio",
        "nombre": "Accidente isquémico transitorio",
        "sistemas": ["neuro"],
        "edad_tipica": [55, 85],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "focalidad_motora": "tipico",
            "afasia": "frecuente",
            "deficit_sensitivo": "frecuente",
            "diplopia": "posible",
            "ataxia": "posible",
            "instauracion_subita": "tipico",
            "alteracion_conciencia": "atipico",
            "cefalea_brusca": "atipico",
            "fiebre": "atipico",
            "lcr_hematico": "incompatible",
            "tabaquismo": "frecuente",
            "anticoagulacion": "posible",
        },
    },
    {
        "id": "epilepsia_focal",
        "nombre": "Epilepsia focal sintomática",
        "sistemas": ["neuro"],
        "edad_tipica": [20, 70],
        "sexo": None,
        "genetica": "Depende de la etiología subyacente; mutaciones en canales iónicos en algunas formas genéticas.",
        "hallazgos": {
            "crisis_convulsiva": "tipico",
            "curso_recurrente": "tipico",
            "alteracion_conciencia": "frecuente",
            "confusion": "frecuente",
            "focalidad_motora": "posible",
            "afasia": "posible",
            "aura_visual": "posible",
            "tc_lesion_ocupante": "posible",
            "rm_temporal": "frecuente",
            "fiebre": "atipico",
            "lcr_purulento": "incompatible",
            "instauracion_subita": "atipico",
        },
    },
    {
        "id": "esclerosis_multiple",
        "nombre": "Esclerosis múltiple remitente-recurrente",
        "sistemas": ["neuro"],
        "edad_tipica": [20, 45],
        "sexo": "predomina_mujer",
        "genetica": "Asociación con HLA-DRB1*15:01; poligénica.",
        "hallazgos": {
            "curso_recurrente": "tipico",
            "deficit_sensitivo": "tipico",
            "focalidad_motora": "frecuente",
            "diplopia": "frecuente",
            "ataxia": "frecuente",
            "alteracion_conducta": "posible",
            "confusion": "atipico",
            "fiebre": "atipico",
            "lcr_pleocitosis_linfo": "frecuente",
            "lcr_proteinorraquia": "frecuente",
            "rm_temporal": "posible",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "absceso_cerebral",
        "nombre": "Absceso cerebral bacteriano",
        "sistemas": ["infecciosas", "neuro"],
        "edad_tipica": [20, 60],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "cefalea_progresiva": "tipico",
            "fiebre": "frecuente",
            "focalidad_motora": "tipico",
            "alteracion_conciencia": "frecuente",
            "crisis_convulsiva": "frecuente",
            "papiledema": "frecuente",
            "vsg_elevada": "frecuente",
            "pcr_elevada": "frecuente",
            "tc_lesion_ocupante": "tipico",
            "foco_orl": "posible",
            "inmunodepresion": "posible",
            "lcr_normal": "atipico",
            "instauracion_subita": "incompatible",
        },
    },
    {
        "id": "hemorragia_intracerebral",
        "nombre": "Hemorragia intraparenquimatosa espontánea",
        "sistemas": ["neuro"],
        "edad_tipica": [55, 80],
        "sexo": None,
        "genetica": "Angiopatía amiloide cerebral en ancianos; mutaciones COL4A1 en formas familiares raras.",
        "hallazgos": {
            "cefalea_brusca": "tipico",
            "instauracion_subita": "tipico",
            "focalidad_motora": "tipico",
            "alteracion_conciencia": "frecuente",
            "vomitos_proyectivos": "frecuente",
            "papiledema": "posible",
            "anticoagulacion": "frecuente",
            "tabaquismo": "posible",
            "tc_hemorragia_subaracnoidea": "atipico",
            "lcr_normal": "atipico",
            "fiebre": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "encefalopatia_hepatica",
        "nombre": "Encefalopatía hepática aguda o crónica",
        "sistemas": ["neuro"],
        "edad_tipica": [45, 75],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "confusion": "tipico",
            "alteracion_conciencia": "tipico",
            "alteracion_conducta": "frecuente",
            "asterixis": "tipico",
            "ictericia": "frecuente",
            "hepatomegalia": "posible",
            "ascitis": "frecuente",
            "amoniaco_elevado": "tipico",
            "tp_alargado": "frecuente",
            "albumina_baja": "frecuente",
            "fiebre": "atipico",
            "lcr_purulento": "incompatible",
            "rigidez_nuca": "incompatible",
        },
    },
    {
        "id": "miastenia_gravis",
        "nombre": "Miastenia gravis autoinmune",
        "sistemas": ["neuro"],
        "edad_tipica": [20, 70],
        "sexo": "predomina_mujer",
        "genetica": "Asociación con HLA-B8 y DR3; anticuerpos anti-AChR o anti-MuSK.",
        "hallazgos": {
            "ptosis_palpebral": "tipico",
            "diplopia": "tipico",
            "disfagia": "frecuente",
            "disnea": "frecuente",
            "fatigabilidad_muscular": "tipico",
            "curso_recurrente": "frecuente",
            "focalidad_motora": "atipico",
            "deficit_sensitivo": "incompatible",
            "alteracion_conciencia": "incompatible",
            "fiebre": "atipico",
            "lcr_pleocitosis_linfo": "atipico",
        },
    },
    {
        "id": "guillain_barre",
        "nombre": "Síndrome de Guillain-Barré clásico",
        "sistemas": ["neuro"],
        "edad_tipica": [30, 70],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante; postinfeccioso autoinmune.",
        "hallazgos": {
            "debilidad_simetrica_ascendente": "tipico",
            "arreflexia": "tipico",
            "parestesias_distales": "frecuente",
            "disfagia": "frecuente",
            "disnea": "frecuente",
            "curso_progresivo": "tipico",
            "instauracion_dias": "tipico",
            "lcr_albuminocitologica": "tipico",
            "lcr_proteinorraquia": "tipico",
            "lcr_pleocitosis_pmn": "incompatible",
            "fiebre": "atipico",
            "alteracion_conciencia": "incompatible",
        },
    },
    {
        "id": "parkinson_idiopatico",
        "nombre": "Enfermedad de Parkinson idiopática",
        "sistemas": ["neuro"],
        "edad_tipica": [55, 80],
        "sexo": "predomina_varon",
        "genetica": "Mutaciones en LRRK2, GBA o SNCA en <10% casos; mayoría esporádica.",
        "hallazgos": {
            "temblor_reposo": "tipico",
            "rigidez_muscular": "tipico",
            "bradicinesia": "tipico",
            "inestabilidad_postural": "frecuente",
            "curso_progresivo": "tipico",
            "micrografia": "frecuente",
            "hipofonia": "frecuente",
            "estrenimiento": "frecuente",
            "anosmia": "frecuente",
            "alteracion_conciencia": "incompatible",
            "fiebre": "atipico",
            "instauracion_subita": "incompatible",
        },
    },
    {
        "id": "demencia_alzheimer",
        "nombre": "Demencia tipo Alzheimer típica",
        "sistemas": ["neuro"],
        "edad_tipica": [65, 90],
        "sexo": "predomina_mujer",
        "genetica": "APOE ε4 factor de riesgo; PSEN1/PSEN2/APP en formas familiares precoces.",
        "hallazgos": {
            "deterioro_memoria_episodica": "tipico",
            "desorientacion_temporoespacial": "frecuente",
            "afasia_anomica": "frecuente",
            "apraxia": "frecuente",
            "agnosia": "posible",
            "alteracion_conducta": "frecuente",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "tipico",
            "tc_normal": "posible",
            "atrofia_hipocampal": "tipico",
            "alteracion_conciencia": "incompatible",
            "fiebre": "atipico",
        },
    },
    {
        "id": "leucemia_linfocitica_cronica",
        "nombre": "Leucemia linfocítica crónica",
        "sistemas": ["oncohemato"],
        "edad_tipica": [60, 85],
        "sexo": "predomina_varon",
        "genetica": "Deleciones 13q, 11q, 17p; trisomía 12; mutaciones TP53, IGHV.",
        "hallazgos": {
            "linfocitosis_absoluta": "tipico",
            "adenopatias_indoloras": "frecuente",
            "esplenomegalia": "frecuente",
            "hepatomegalia": "posible",
            "anemia": "frecuente",
            "trombopenia": "posible",
            "infecciones_recurrentes": "frecuente",
            "perdida_peso": "posible",
            "sudoracion_nocturna": "posible",
            "blastos_sangre": "incompatible",
        },
    },
    {
        "id": "linfoma_no_hodgkin_agresivo",
        "nombre": "Linfoma no Hodgkin agresivo (DLBCL)",
        "sistemas": ["oncohemato"],
        "edad_tipica": [50, 80],
        "sexo": None,
        "genetica": "Reordenamientos BCL6, MYC; mutaciones en EZH2, CREBBP.",
        "hallazgos": {
            "adenopatias_indoloras": "tipico",
            "masa_extranodal": "frecuente",
            "perdida_peso": "frecuente",
            "sudoracion_nocturna": "frecuente",
            "fiebre": "frecuente",
            "ldh_elevada": "tipico",
            "vsg_elevada": "frecuente",
            "anemia": "frecuente",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "tipico",
            "blastos_sangre": "atipico",
            "lcr_normal": "posible",
        },
    },
    {
        "id": "mieloma_multiple",
        "nombre": "Mieloma múltiple sintomático",
        "sistemas": ["oncohemato"],
        "edad_tipica": [60, 85],
        "sexo": "predomina_varon",
        "genetica": "Translocaciones IgH (11q13, 4p16); del(17p), amp(1q); sin herencia mendeliana.",
        "hallazgos": {
            "dolor_oseo": "tipico",
            "anemia": "tipico",
            "insuficiencia_renal": "frecuente",
            "hipercalcemia": "frecuente",
            "proteina_monoclonal": "tipico",
            "cadenas_ligeras_libres": "tipico",
            "lesiones_liticas": "tipico",
            "fracturas_patologicas": "frecuente",
            "infecciones_recurrentes": "frecuente",
            "blastos_sangre": "incompatible",
            "adenopatias_generalizadas": "atipico",
        },
    },
    {
        "id": "sepsis_urinaria",
        "nombre": "Sepsis de origen urinario",
        "sistemas": ["infecciosas"],
        "edad_tipica": [60, 90],
        "sexo": "predomina_mujer",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre": "tipico",
            "escalofrios": "frecuente",
            "disuria": "tipico",
            "dolor_suprapubico": "frecuente",
            "dolor_lumbar": "frecuente",
            "taquicardia": "tipico",
            "hipotension": "frecuente",
            "leucocitosis": "tipico",
            "pcr_elevada": "tipico",
            "procalcitonina_elevada": "tipico",
            "urocultivo_positivo": "tipico",
            "lcr_purulento": "incompatible",
            "petequias": "atipico",
        },
    },
    {
        "id": "endocarditis_infecciosa",
        "nombre": "Endocarditis infecciosa subaguda",
        "sistemas": ["infecciosas"],
        "edad_tipica": [40, 80],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre_prolongada": "tipico",
            "soplo_cardiaco_nuevo": "tipico",
            "fenomenos_embolicos": "frecuente",
            "petequias": "frecuente",
            "nodos_osler": "posible",
            "manchas_janeway": "posible",
            "esplenomegalia": "frecuente",
            "anemia": "frecuente",
            "vsg_elevada": "tipico",
            "pcr_elevada": "tipico",
            "hemocultivos_positivos": "tipico",
            "ecocardiograma_vegetaciones": "tipico",
            "lcr_purulento": "incompatible",
            "instauracion_subita": "atipico",
        },
    },
    {
        "id": "ictus_isquemico",
        "nombre": "Ictus isquémico agudo",
        "sistemas": ["neuro"],
        "edad_tipica": [55, 85],
        "sexo": None,
        "genetica": "Sin base genética relevante; los factores de riesgo vasculares pesan mucho más.",
        "hallazgos": {
            "instauracion_subita": "tipico",
            "focalidad_motora": "tipico",
            "afasia": "frecuente",
            "deficit_sensitivo": "frecuente",
            "diplopia": "posible",
            "ataxia": "posible",
            "alteracion_conciencia": "posible",
            "tabaquismo": "frecuente",
            "anticoagulacion": "posible",
            "tc_normal": "frecuente",
            "cefalea_progresiva": "atipico",
            "fiebre": "atipico",
            "instauracion_semanas": "atipico",
            "lcr_hematico": "incompatible",
        },
    },
    {
        "id": "vih_agudo",
        "nombre": "Infección aguda por VIH",
        "sistemas": ["infecciosas"],
        "edad_tipica": [20, 45],
        "sexo": None,
        "genetica": "Sin base genética relevante; el CCR5-delta32 confiere resistencia parcial.",
        "hallazgos": {
            "fiebre": "tipico",
            "odinofagia": "frecuente",
            "exantema": "frecuente",
            "adenopatias_generalizadas": "frecuente",
            "astenia": "frecuente",
            "malestar_general": "frecuente",
            "transaminasas_elevadas": "frecuente",
            "instauracion_dias": "frecuente",
            "leucopenia": "posible",
            "trombopenia": "posible",
            "linfocitosis": "posible",
            "diarrea": "posible",
            "lcr_pleocitosis_linfo": "posible",
            "instauracion_subita": "atipico",
            "instauracion_semanas": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "celulitis_erisipela",
        "nombre": "Celulitis / Erisipela",
        "sistemas": ["infecciosas"],
        "edad_tipica": [40, 85],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre": "frecuente",
            "escalofrios": "frecuente",
            "malestar_general": "frecuente",
            "instauracion_dias": "tipico",
            "leucocitosis": "frecuente",
            "neutrofilia": "frecuente",
            "pcr_elevada": "frecuente",
            "procalcitonina_elevada": "posible",
            "vsg_elevada": "frecuente",
            "taquicardia": "frecuente",
            "dolor_oseo": "atipico",
            "lcr_purulento": "incompatible",
            "tos": "atipico",
            "diarrea": "atipico",
        },
    },
    {
        "id": "pielonefritis_aguda",
        "nombre": "Pielonefritis aguda",
        "sistemas": ["infecciosas"],
        "edad_tipica": [20, 70],
        "sexo": "predomina_mujer",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre": "tipico",
            "escalofrios": "frecuente",
            "dolor_lumbar": "tipico",
            "disuria": "frecuente",
            "malestar_general": "frecuente",
            "leucocitosis": "tipico",
            "neutrofilia": "tipico",
            "pcr_elevada": "tipico",
            "procalcitonina_elevada": "frecuente",
            "urocultivo_positivo": "tipico",
            "hemocultivos_positivos": "posible",
            "insuficiencia_renal": "posible",
            "nauseas_vomitos": "frecuente",
            "cefalea_brusca": "atipico",
            "rigidez_nuca": "atipico",
            "exantema": "atipico",
        },
    },
    {
        "id": "colangitis_aguda",
        "nombre": "Colangitis aguda ascendente",
        "sistemas": ["infecciosas"],
        "edad_tipica": [50, 85],
        "sexo": "predomina_mujer",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre": "tipico",
            "ictericia": "tipico",
            "dolor_abdominal": "tipico",
            "escalofrios": "frecuente",
            "hipotension": "frecuente",
            "confusion": "frecuente",
            "leucocitosis": "tipico",
            "neutrofilia": "tipico",
            "pcr_elevada": "tipico",
            "procalcitonina_elevada": "tipico",
            "hemocultivos_positivos": "frecuente",
            "insuficiencia_renal": "posible",
            "tp_alargado": "posible",
            "transaminasas_elevadas": "frecuente",
            "lcr_purulento": "incompatible",
            "cefalea_brusca": "atipico",
            "dolor_lumbar": "atipico",
        },
    },
    {
        "id": "gastroenteritis_bacteriana",
        "nombre": "Gastroenteritis bacteriana aguda",
        "sistemas": ["infecciosas"],
        "edad_tipica": [0, 90],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "diarrea": "tipico",
            "fiebre": "frecuente",
            "dolor_abdominal": "tipico",
            "nauseas_vomitos": "frecuente",
            "malestar_general": "frecuente",
            "astenia": "frecuente",
            "instauracion_horas": "tipico",
            "leucocitosis": "posible",
            "pcr_elevada": "posible",
            "contacto_epidemico": "frecuente",
            "viaje_reciente": "posible",
            "rigidez_nuca": "atipico",
            "lcr_purulento": "incompatible",
            "tos": "atipico",
            "hemoptisis": "atipico",
        },
    },
    {
        "id": "dengue",
        "nombre": "Dengue",
        "sistemas": ["infecciosas"],
        "edad_tipica": [5, 60],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre": "tipico",
            "malestar_general": "tipico",
            "mialgias": "tipico",
            "artralgias": "tipico",
            "exantema": "frecuente",
            "petequias": "frecuente",
            "leucopenia": "tipico",
            "trombopenia": "tipico",
            "transaminasas_elevadas": "frecuente",
            "pcr_elevada": "posible",
            "viaje_reciente": "tipico",
            "instauracion_subita": "tipico",
            "hepatomegalia": "posible",
            "hemocultivos_positivos": "atipico",
            "lcr_purulento": "incompatible",
            "expectoracion": "atipico",
        },
    },
    {
        "id": "malaria_falciparum",
        "nombre": "Malaria por Plasmodium falciparum",
        "sistemas": ["infecciosas"],
        "edad_tipica": [1, 70],
        "sexo": None,
        "genetica": "El rasgo falciforme y la talasemia protegen frente a las formas graves.",
        "hallazgos": {
            "fiebre": "tipico",
            "escalofrios": "tipico",
            "sudoracion_nocturna": "frecuente",
            "esplenomegalia": "frecuente",
            "hepatomegalia": "frecuente",
            "anemia": "tipico",
            "trombopenia": "frecuente",
            "ictericia": "frecuente",
            "confusion": "posible",
            "viaje_reciente": "tipico",
            "insuficiencia_renal": "posible",
            "mialgias": "frecuente",
            "lcr_purulento": "incompatible",
            "adenopatias_generalizadas": "atipico",
            "hemocultivos_positivos": "atipico",
        },
    },
    {
        "id": "fiebre_tifoidea",
        "nombre": "Fiebre tifoidea",
        "sistemas": ["infecciosas"],
        "edad_tipica": [5, 50],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre_prolongada": "tipico",
            "cefalea_progresiva": "frecuente",
            "dolor_abdominal": "frecuente",
            "estrenimiento": "frecuente",
            "hepatomegalia": "frecuente",
            "esplenomegalia": "frecuente",
            "leucopenia": "frecuente",
            "anemia": "posible",
            "viaje_reciente": "tipico",
            "hemocultivos_positivos": "tipico",
            "exantema": "posible",
            "transaminasas_elevadas": "frecuente",
            "lcr_purulento": "incompatible",
            "instauracion_subita": "atipico",
            "petequias": "atipico",
        },
    },
    {
        "id": "brucelosis",
        "nombre": "Brucelosis",
        "sistemas": ["infecciosas"],
        "edad_tipica": [20, 60],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre_prolongada": "tipico",
            "sudoracion_nocturna": "tipico",
            "astenia": "tipico",
            "dolor_oseo": "frecuente",
            "artralgias": "frecuente",
            "hepatomegalia": "frecuente",
            "esplenomegalia": "frecuente",
            "leucopenia": "frecuente",
            "anemia": "posible",
            "vsg_elevada": "frecuente",
            "pcr_elevada": "posible",
            "hemocultivos_positivos": "frecuente",
            "contacto_epidemico": "frecuente",
            "lcr_purulento": "incompatible",
            "instauracion_subita": "atipico",
            "exantema": "atipico",
        },
    },
    {
        "id": "leptospirosis",
        "nombre": "Leptospirosis",
        "sistemas": ["infecciosas"],
        "edad_tipica": [15, 60],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre": "tipico",
            "ictericia": "tipico",
            "insuficiencia_renal": "tipico",
            "mialgias": "tipico",
            "dolor_lumbar": "frecuente",
            "hemoptisis": "posible",
            "petequias": "frecuente",
            "leucocitosis": "frecuente",
            "neutrofilia": "frecuente",
            "tp_alargado": "frecuente",
            "albumina_baja": "posible",
            "transaminasas_elevadas": "frecuente",
            "viaje_reciente": "posible",
            "lcr_purulento": "incompatible",
            "adenopatias_generalizadas": "atipico",
            "curso_recurrente": "atipico",
        },
    },
    {
        "id": "vih_sintomatico",
        "nombre": "Infección sintomática por VIH avanzada",
        "sistemas": ["infecciosas"],
        "edad_tipica": [20, 50],
        "sexo": None,
        "genetica": "Sin base genética relevante; el CCR5-delta32 confiere resistencia parcial.",
        "hallazgos": {
            "fiebre_prolongada": "frecuente",
            "perdida_peso": "frecuente",
            "sudoracion_nocturna": "frecuente",
            "adenopatias_generalizadas": "tipico",
            "diarrea": "frecuente",
            "candidiasis_oral": "tipico",
            "leucopenia": "frecuente",
            "trombopenia": "frecuente",
            "anemia": "frecuente",
            "ldh_elevada": "posible",
            "vih": "tipico",
            "infecciones_recurrentes": "frecuente",
            "instauracion_semanas": "frecuente",
            "lcr_purulento": "incompatible",
            "instauracion_subita": "atipico",
            "blastos_sangre": "incompatible",
        },
    },
    {
        "id": "sifilis_secundaria",
        "nombre": "Sífilis secundaria",
        "sistemas": ["infecciosas"],
        "edad_tipica": [20, 50],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "exantema": "tipico",
            "adenopatias_generalizadas": "tipico",
            "alopecia_parcheada": "frecuente",
            "fiebre": "frecuente",
            "malestar_general": "frecuente",
            "odinofagia": "posible",
            "hepatomegalia": "posible",
            "esplenomegalia": "posible",
            "vsg_elevada": "frecuente",
            "pcr_elevada": "posible",
            "advp": "posible",
            "vih": "posible",
            "lcr_purulento": "incompatible",
            "instauracion_subita": "atipico",
            "neutrofilia": "atipico",
        },
    },
    {
        "id": "histoplasmosis_diseminada",
        "nombre": "Histoplasmosis diseminada",
        "sistemas": ["infecciosas"],
        "edad_tipica": [30, 70],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre_prolongada": "tipico",
            "perdida_peso": "tipico",
            "hepatomegalia": "frecuente",
            "esplenomegalia": "frecuente",
            "pancitopenia": "frecuente",
            "adenopatias_generalizadas": "frecuente",
            "inmunodepresion": "tipico",
            "vih": "frecuente",
            "ldh_elevada": "frecuente",
            "albumina_baja": "frecuente",
            "viaje_reciente": "posible",
            "lcr_purulento": "incompatible",
            "instauracion_subita": "atipico",
            "neutrofilia": "atipico",
        },
    },
    {
        "id": "toxoplasmosis_cerebral",
        "nombre": "Toxoplasmosis cerebral en VIH",
        "sistemas": ["infecciosas", "neuro"],
        "edad_tipica": [25, 55],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "cefalea_progresiva": "tipico",
            "focalidad_motora": "tipico",
            "fiebre": "frecuente",
            "alteracion_conciencia": "frecuente",
            "crisis_convulsiva": "frecuente",
            "confusion": "frecuente",
            "vih": "tipico",
            "inmunodepresion": "tipico",
            "tc_lesion_ocupante": "tipico",
            "lcr_pleocitosis_linfo": "posible",
            "lcr_proteinorraquia": "frecuente",
            "instauracion_dias": "frecuente",
            "lcr_purulento": "incompatible",
            "instauracion_subita": "atipico",
            "lcr_normal": "atipico",
        },
    },
    {
        "id": "candidiasis_invasiva",
        "nombre": "Candidiasis invasiva",
        "sistemas": ["infecciosas"],
        "edad_tipica": [40, 85],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre_prolongada": "tipico",
            "escalofrios": "frecuente",
            "hipotension": "frecuente",
            "inmunodepresion": "tipico",
            "quimioterapia_previa": "frecuente",
            "neutropenia": "frecuente",
            "leucocitosis": "frecuente",
            "neutrofilia": "frecuente",
            "pcr_elevada": "tipico",
            "procalcitonina_elevada": "posible",
            "hemocultivos_positivos": "tipico",
            "insuficiencia_renal": "posible",
            "lcr_purulento": "incompatible",
            "petequias": "atipico",
            "instauracion_subita": "atipico",
        },
    },
    {
        "id": "aspergilosis_invasiva",
        "nombre": "Aspergilosis invasiva pulmonar",
        "sistemas": ["infecciosas"],
        "edad_tipica": [40, 80],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "fiebre_prolongada": "tipico",
            "tos": "frecuente",
            "hemoptisis": "frecuente",
            "dolor_pleuritico": "frecuente",
            "disnea": "frecuente",
            "rx_condensacion": "tipico",
            "inmunodepresion": "tipico",
            "neutropenia": "tipico",
            "quimioterapia_previa": "frecuente",
            "pcr_elevada": "frecuente",
            "lcr_purulento": "incompatible",
            "hemocultivos_positivos": "atipico",
            "instauracion_subita": "atipico",
            "adenopatias_generalizadas": "atipico",
        },
    },
    {
        "id": "leucemia_mieloide_cronica",
        "nombre": "Leucemia mieloide crónica",
        "sistemas": ["oncohemato"],
        "edad_tipica": [45, 75],
        "sexo": "predomina_varon",
        "genetica": "Translocación t(9;22) BCR-ABL1 (cromosoma Filadelfia) en más del 95% de los casos.",
        "hallazgos": {
            "leucocitosis": "tipico",
            "esplenomegalia": "tipico",
            "basofilia": "tipico",
            "astenia": "frecuente",
            "perdida_peso": "frecuente",
            "sudoracion_nocturna": "frecuente",
            "anemia": "frecuente",
            "ldh_elevada": "frecuente",
            "acido_urico_elevado": "frecuente",
            "trombopenia": "posible",
            "hepatomegalia": "posible",
            "blastos_sangre": "posible",
            "dolor_oseo": "atipico",
            "adenopatias_generalizadas": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "policitemia_vera",
        "nombre": "Policitemia vera",
        "sistemas": ["oncohemato"],
        "edad_tipica": [55, 80],
        "sexo": None,
        "genetica": "Mutación JAK2 V617F en más del 95%; exón 12 de JAK2 en menos del 3%.",
        "hallazgos": {
            "eritrocitosis": "tipico",
            "prurito": "tipico",
            "esplenomegalia": "frecuente",
            "cefalea_progresiva": "frecuente",
            "leucocitosis": "frecuente",
            "trombocitosis": "frecuente",
            "hipertension": "frecuente",
            "fenomenos_embolicos": "frecuente",
            "acido_urico_elevado": "frecuente",
            "hepatomegalia": "posible",
            "fiebre": "atipico",
            "adenopatias_generalizadas": "atipico",
            "anemia": "incompatible",
            "pancitopenia": "incompatible",
        },
    },
    {
        "id": "trombocitemia_esencial",
        "nombre": "Trombocitemia esencial",
        "sistemas": ["oncohemato"],
        "edad_tipica": [50, 80],
        "sexo": "predomina_mujer",
        "genetica": "JAK2 V617F en torno al 55%, CALR 25%, MPL 5%; triple negativo el 15%.",
        "hallazgos": {
            "trombocitosis": "tipico",
            "eritromelalgia": "tipico",
            "fenomenos_embolicos": "frecuente",
            "sangrado_mucosas": "frecuente",
            "cefalea_progresiva": "frecuente",
            "esplenomegalia": "frecuente",
            "leucocitosis": "posible",
            "anemia": "atipico",
            "fiebre": "atipico",
            "adenopatias_generalizadas": "atipico",
            "dolor_oseo": "atipico",
            "blastos_sangre": "atipico",
            "pancitopenia": "incompatible",
        },
    },
    {
        "id": "mielofibrosis_primaria",
        "nombre": "Mielofibrosis primaria",
        "sistemas": ["oncohemato"],
        "edad_tipica": [60, 80],
        "sexo": None,
        "genetica": "JAK2 V617F en torno al 50%, CALR 30%, MPL 10%; ASXL1 y EZH2 de mal pronóstico.",
        "hallazgos": {
            "esplenomegalia": "tipico",
            "leucoeritroblastosis": "tipico",
            "dacriocitos": "tipico",
            "anemia": "tipico",
            "astenia": "tipico",
            "perdida_peso": "frecuente",
            "sudoracion_nocturna": "frecuente",
            "ldh_elevada": "frecuente",
            "hepatomegalia": "frecuente",
            "dolor_oseo": "posible",
            "pancitopenia": "posible",
            "blastos_sangre": "posible",
            "instauracion_semanas": "frecuente",
            "adenopatias_generalizadas": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "sindrome_mielodisplasico",
        "nombre": "Síndrome mielodisplásico",
        "sistemas": ["oncohemato"],
        "edad_tipica": [65, 90],
        "sexo": "predomina_varon",
        "genetica": "del(5q), -7/del(7q), +8, del(20q); mutaciones SF3B1, TET2, ASXL1, TP53.",
        "hallazgos": {
            "anemia": "tipico",
            "macrocitosis": "tipico",
            "displasia_medular": "tipico",
            "palidez": "tipico",
            "pancitopenia": "frecuente",
            "neutropenia": "frecuente",
            "trombopenia": "frecuente",
            "infecciones_recurrentes": "frecuente",
            "sangrado_mucosas": "frecuente",
            "equimosis": "frecuente",
            "instauracion_semanas": "frecuente",
            "blastos_sangre": "posible",
            "esplenomegalia": "atipico",
            "adenopatias_generalizadas": "atipico",
            "hipercalcemia": "atipico",
        },
    },
    {
        "id": "linfoma_folicular",
        "nombre": "Linfoma folicular",
        "sistemas": ["oncohemato"],
        "edad_tipica": [50, 75],
        "sexo": None,
        "genetica": "Translocación t(14;18) BCL2-IGH en más del 85%, con sobreexpresión de BCL2.",
        "hallazgos": {
            "adenopatias_indoloras": "tipico",
            "curso_recurrente": "tipico",
            "instauracion_semanas": "tipico",
            "adenopatias_generalizadas": "frecuente",
            "esplenomegalia": "frecuente",
            "ldh_elevada": "posible",
            "anemia": "posible",
            "masa_extranodal": "posible",
            "perdida_peso": "atipico",
            "sudoracion_nocturna": "atipico",
            "fiebre": "atipico",
            "blastos_sangre": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "linfoma_manto",
        "nombre": "Linfoma de células del manto",
        "sistemas": ["oncohemato"],
        "edad_tipica": [55, 75],
        "sexo": "predomina_varon",
        "genetica": "Translocación t(11;14) CCND1-IGH con sobreexpresión de ciclina D1; SOX11 positivo.",
        "hallazgos": {
            "adenopatias_indoloras": "tipico",
            "curso_progresivo": "tipico",
            "adenopatias_generalizadas": "frecuente",
            "esplenomegalia": "frecuente",
            "hepatomegalia": "frecuente",
            "masa_extranodal": "frecuente",
            "ldh_elevada": "frecuente",
            "anemia": "frecuente",
            "perdida_peso": "frecuente",
            "blastos_sangre": "posible",
            "fiebre": "atipico",
            "hipercalcemia": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "linfoma_burkitt",
        "nombre": "Linfoma de Burkitt",
        "sistemas": ["oncohemato"],
        "edad_tipica": [5, 40],
        "sexo": "predomina_varon",
        "genetica": "Translocación t(8;14) MYC-IGH en más del 80%; variantes t(2;8) y t(8;22). Ki67 cercano al 100%.",
        "hallazgos": {
            "masa_extranodal": "tipico",
            "masa_palpable": "tipico",
            "instauracion_dias": "tipico",
            "curso_progresivo": "tipico",
            "ldh_elevada": "tipico",
            "acido_urico_elevado": "tipico",
            "dolor_abdominal": "frecuente",
            "nauseas_vomitos": "frecuente",
            "anemia": "frecuente",
            "vih": "posible",
            "blastos_sangre": "posible",
            "instauracion_semanas": "atipico",
            "curso_recurrente": "atipico",
        },
    },
    {
        "id": "macroglobulinemia_waldenstrom",
        "nombre": "Macroglobulinemia de Waldenström",
        "sistemas": ["oncohemato"],
        "edad_tipica": [60, 85],
        "sexo": "predomina_varon",
        "genetica": "Mutación MYD88 L265P en más del 90%; CXCR4 en torno al 30%.",
        "hallazgos": {
            "proteina_monoclonal": "tipico",
            "hiperviscosidad": "tipico",
            "anemia": "tipico",
            "vsg_elevada": "tipico",
            "adenopatias_indoloras": "frecuente",
            "esplenomegalia": "frecuente",
            "hepatomegalia": "frecuente",
            "sangrado_mucosas": "frecuente",
            "neuropatia_periferica": "frecuente",
            "cefalea_progresiva": "posible",
            "insuficiencia_renal": "atipico",
            "lesiones_liticas": "incompatible",
            "hipercalcemia": "incompatible",
        },
    },
    {
        "id": "shu_atipico",
        "nombre": "Síndrome hemolítico urémico atípico",
        "sistemas": ["oncohemato"],
        "edad_tipica": [0, 60],
        "sexo": None,
        "genetica": "Mutaciones del complemento (CFH, CFI, MCP, C3, CFB), autosómicas dominantes con penetrancia incompleta.",
        "hallazgos": {
            "esquistocitos": "tipico",
            "anemia": "tipico",
            "trombopenia": "tipico",
            "insuficiencia_renal": "tipico",
            "hipertension": "frecuente",
            "dolor_abdominal": "frecuente",
            "ldh_elevada": "frecuente",
            "confusion": "posible",
            "diarrea": "atipico",
            "fiebre": "atipico",
            "adenopatias_generalizadas": "atipico",
            "blastos_sangre": "incompatible",
            "tp_alargado": "incompatible",
        },
    },
    {
        "id": "pti",
        "nombre": "Púrpura trombocitopénica inmune",
        "sistemas": ["oncohemato"],
        "edad_tipica": [20, 60],
        "sexo": "predomina_mujer",
        "genetica": "Sin base genética relevante; autoanticuerpos anti-GPIIb/IIIa o anti-GPIb/IX.",
        "hallazgos": {
            "trombopenia": "tipico",
            "petequias": "tipico",
            "equimosis": "frecuente",
            "sangrado_mucosas": "frecuente",
            "anemia": "posible",
            "esplenomegalia": "atipico",
            "leucocitosis": "atipico",
            "fiebre": "atipico",
            "dolor_oseo": "atipico",
            "adenopatias_generalizadas": "incompatible",
            "blastos_sangre": "incompatible",
            "pancitopenia": "incompatible",
        },
    },
    {
        "id": "cid",
        "nombre": "Coagulación intravascular diseminada",
        "sistemas": ["oncohemato"],
        "edad_tipica": [0, 90],
        "sexo": None,
        "genetica": "Sin base genética relevante; es secundaria a sepsis, traumatismo, cáncer o complicación obstétrica.",
        "hallazgos": {
            "tp_alargado": "tipico",
            "hipofibrinogenemia": "tipico",
            "trombopenia": "tipico",
            "equimosis": "tipico",
            "sangrado_mucosas": "tipico",
            "esquistocitos": "frecuente",
            "anemia": "frecuente",
            "insuficiencia_renal": "frecuente",
            "hipotension": "frecuente",
            "instauracion_horas": "frecuente",
            "confusion": "posible",
            "blastos_sangre": "atipico",
            "curso_recurrente": "atipico",
            "adenopatias_generalizadas": "atipico",
        },
    },
    {
        "id": "anemia_aplasica",
        "nombre": "Anemia aplásica adquirida",
        "sistemas": ["oncohemato"],
        "edad_tipica": [15, 60],
        "sexo": None,
        "genetica": "Sin base genética relevante en la forma adquirida; pueden aparecer clones somáticos PIG-A, BCOR o ASXL1.",
        "hallazgos": {
            "pancitopenia": "tipico",
            "anemia": "tipico",
            "neutropenia": "tipico",
            "trombopenia": "tipico",
            "palidez": "tipico",
            "equimosis": "frecuente",
            "sangrado_mucosas": "frecuente",
            "infecciones_recurrentes": "frecuente",
            "astenia": "frecuente",
            "dolor_oseo": "atipico",
            "hepatomegalia": "atipico",
            "esplenomegalia": "incompatible",
            "adenopatias_generalizadas": "incompatible",
            "blastos_sangre": "incompatible",
        },
    },
    {
        "id": "lisis_tumoral",
        "nombre": "Síndrome de lisis tumoral",
        "sistemas": ["oncohemato"],
        "edad_tipica": [5, 70],
        "sexo": None,
        "genetica": "Sin base genética relevante; es una complicación metabólica de tumores de proliferación rápida tras el tratamiento.",
        "hallazgos": {
            "hiperpotasemia": "tipico",
            "hiperfosfatemia": "tipico",
            "hipocalcemia": "tipico",
            "acido_urico_elevado": "tipico",
            "insuficiencia_renal": "tipico",
            "quimioterapia_previa": "tipico",
            "instauracion_horas": "tipico",
            "nauseas_vomitos": "frecuente",
            "confusion": "frecuente",
            "taquicardia": "frecuente",
            "ldh_elevada": "frecuente",
            "crisis_convulsiva": "posible",
            "fiebre": "atipico",
            "instauracion_semanas": "atipico",
        },
    },
    {
        "id": "leucemia_promielocitica",
        "nombre": "Leucemia promielocítica aguda",
        "sistemas": ["oncohemato"],
        "edad_tipica": [25, 55],
        "sexo": None,
        "genetica": "Translocación t(15;17) PML-RARA; la variante t(11;17) PLZF-RARA es resistente al ATRA.",
        "hallazgos": {
            "blastos_sangre": "tipico",
            "tp_alargado": "tipico",
            "hipofibrinogenemia": "tipico",
            "equimosis": "tipico",
            "sangrado_mucosas": "tipico",
            "pancitopenia": "tipico",
            "anemia": "tipico",
            "trombopenia": "tipico",
            "neutropenia": "tipico",
            "instauracion_dias": "tipico",
            "fiebre": "frecuente",
            "palidez": "frecuente",
            "adenopatias_generalizadas": "atipico",
            "esplenomegalia": "atipico",
            "masa_mediastinica": "atipico",
        },
    },
    {
        "id": "delirium",
        "nombre": "Delirium (síndrome confusional agudo)",
        "sistemas": ["neuro"],
        "edad_tipica": [65, 95],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "confusion": "tipico",
            "atencion_fluctuante": "tipico",
            "alteracion_conciencia": "tipico",
            "instauracion_horas": "tipico",
            "inversion_ciclo_sueno": "frecuente",
            "alucinaciones_visuales": "frecuente",
            "alteracion_conducta": "frecuente",
            "infecciones_recurrentes": "posible",
            "fiebre": "posible",
            "taquicardia": "posible",
            "instauracion_dias": "posible",
            "deterioro_memoria_episodica": "atipico",
            "curso_progresivo": "atipico",
            "papiledema": "atipico",
        },
    },
    {
        "id": "demencia_cuerpos_lewy",
        "nombre": "Demencia por cuerpos de Lewy",
        "sistemas": ["neuro"],
        "edad_tipica": [60, 85],
        "sexo": "predomina_varon",
        "genetica": "Depósito de alfa-sinucleína; mutaciones SNCA o GBA en una minoría, el resto esporádicas.",
        "hallazgos": {
            "alucinaciones_visuales": "tipico",
            "fluctuacion_cognitiva": "tipico",
            "trastorno_conducta_rem": "tipico",
            "sensibilidad_neurolepticos": "tipico",
            "rigidez_muscular": "frecuente",
            "bradicinesia": "frecuente",
            "caidas_precoces": "frecuente",
            "sincope": "frecuente",
            "confusion": "frecuente",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "frecuente",
            "temblor_reposo": "atipico",
            "instauracion_subita": "incompatible",
        },
    },
    {
        "id": "demencia_frontotemporal",
        "nombre": "Demencia frontotemporal (variante conductual)",
        "sistemas": ["neuro"],
        "edad_tipica": [45, 70],
        "sexo": None,
        "genetica": "Mutaciones en C9orf72, MAPT o GRN en torno al 30%, con herencia autosómica dominante frecuente.",
        "hallazgos": {
            "desinhibicion_social": "tipico",
            "perdida_empatia": "tipico",
            "apatia": "tipico",
            "alteracion_conducta": "tipico",
            "conducta_compulsiva": "frecuente",
            "hiperoralidad": "frecuente",
            "afasia_no_fluyente": "posible",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "tipico",
            "deterioro_memoria_episodica": "atipico",
            "desorientacion_temporoespacial": "atipico",
            "alucinaciones_visuales": "atipico",
            "tc_lesion_ocupante": "incompatible",
        },
    },
    {
        "id": "hidrocefalia_normotensiva",
        "nombre": "Hidrocefalia normotensiva del adulto",
        "sistemas": ["neuro"],
        "edad_tipica": [60, 85],
        "sexo": None,
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "marcha_apraxica": "tipico",
            "incontinencia_urinaria": "tipico",
            "deterioro_cognitivo_ejecutivo": "tipico",
            "ataxia": "frecuente",
            "ventriculomegalia": "tipico",
            "lcr_normal": "tipico",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "tipico",
            "inestabilidad_postural": "frecuente",
            "focalidad_motora": "atipico",
            "crisis_convulsiva": "atipico",
            "cefalea_brusca": "atipico",
            "papiledema": "incompatible",
        },
    },
    {
        "id": "paralisis_supranuclear_progresiva",
        "nombre": "Parálisis supranuclear progresiva",
        "sistemas": ["neuro"],
        "edad_tipica": [55, 75],
        "sexo": "predomina_varon",
        "genetica": "Tauopatía 4R esporádica; el haplotipo H1 de MAPT es factor de riesgo.",
        "hallazgos": {
            "oftalmoplejia_supranuclear": "tipico",
            "caidas_precoces": "tipico",
            "rigidez_axial": "tipico",
            "inestabilidad_postural": "tipico",
            "bradicinesia": "frecuente",
            "disfagia": "frecuente",
            "disartria": "frecuente",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "tipico",
            "deterioro_cognitivo_ejecutivo": "frecuente",
            "temblor_reposo": "atipico",
            "respuesta_levodopa": "atipico",
            "alucinaciones_visuales": "atipico",
        },
    },
    {
        "id": "esclerosis_lateral_amiotrofica",
        "nombre": "Esclerosis lateral amiotrófica",
        "sistemas": ["neuro"],
        "edad_tipica": [50, 75],
        "sexo": "predomina_varon",
        "genetica": "Mutaciones en C9orf72, SOD1, TARDBP o FUS en torno al 10%; el resto esporádicas.",
        "hallazgos": {
            "debilidad_progresiva_asimetrica": "tipico",
            "fasciculaciones": "tipico",
            "hiperreflexia": "tipico",
            "signo_babinski": "tipico",
            "atrofia_muscular": "tipico",
            "disfagia": "frecuente",
            "disartria": "frecuente",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "tipico",
            "disnea": "posible",
            "diplopia": "atipico",
            "curso_recurrente": "atipico",
            "deficit_sensitivo": "incompatible",
            "alteracion_conciencia": "incompatible",
        },
    },
    {
        "id": "mielopatia_cervical",
        "nombre": "Mielopatía cervical espondilótica",
        "sistemas": ["neuro"],
        "edad_tipica": [50, 80],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "torpeza_manual": "tipico",
            "marcha_espastica": "tipico",
            "hiperreflexia": "tipico",
            "signo_babinski": "frecuente",
            "dolor_cervical": "frecuente",
            "parestesias_distales": "frecuente",
            "nivel_sensitivo": "posible",
            "lhermitte": "posible",
            "incontinencia_urinaria": "posible",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "tipico",
            "fiebre": "atipico",
            "alteracion_conciencia": "incompatible",
            "crisis_convulsiva": "incompatible",
        },
    },
    {
        "id": "neuritis_optica",
        "nombre": "Neuritis óptica",
        "sistemas": ["neuro"],
        "edad_tipica": [20, 45],
        "sexo": "predomina_mujer",
        "genetica": "Asociación con HLA-DRB1*15:01; anticuerpos anti-MOG o anti-AQP4 en las variantes.",
        "hallazgos": {
            "perdida_vision_unilateral": "tipico",
            "dolor_ocular_movimiento": "tipico",
            "discromatopsia": "tipico",
            "deficit_pupilar_aferente": "tipico",
            "instauracion_dias": "tipico",
            "rm_nervio_optico": "tipico",
            "curso_recurrente": "posible",
            "lcr_pleocitosis_linfo": "posible",
            "lcr_proteinorraquia": "posible",
            "papiledema": "posible",
            "diplopia": "atipico",
            "fiebre": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "vppb",
        "nombre": "Vértigo posicional paroxístico benigno",
        "sistemas": ["neuro"],
        "edad_tipica": [40, 80],
        "sexo": "predomina_mujer",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "vertigo_posicional": "tipico",
            "dix_hallpike_positivo": "tipico",
            "nistagmo_posicional": "tipico",
            "curso_recurrente": "tipico",
            "instauracion_subita": "tipico",
            "nauseas_vomitos": "frecuente",
            "hipoacusia": "atipico",
            "cefalea_progresiva": "atipico",
            "alteracion_conciencia": "atipico",
            "ataxia": "atipico",
            "acufenos": "incompatible",
            "focalidad_motora": "incompatible",
        },
    },
    {
        "id": "radiculopatia_lumbar",
        "nombre": "Radiculopatía lumbar por hernia discal",
        "sistemas": ["neuro"],
        "edad_tipica": [30, 60],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante.",
        "hallazgos": {
            "dolor_lumbar_irradiado": "tipico",
            "lassegue_positivo": "tipico",
            "valsalva_agrava": "tipico",
            "deficit_motor_radicular": "frecuente",
            "parestesias_distales": "frecuente",
            "arreflexia": "frecuente",
            "instauracion_subita": "frecuente",
            "instauracion_dias": "frecuente",
            "anestesia_silla_montar": "posible",
            "incontinencia_urinaria": "posible",
            "fiebre": "atipico",
            "perdida_peso": "atipico",
            "alteracion_conciencia": "incompatible",
            "lcr_pleocitosis_pmn": "incompatible",
        },
    },
    {
        "id": "polineuropatia_diabetica",
        "nombre": "Polineuropatía diabética distal simétrica",
        "sistemas": ["neuro"],
        "edad_tipica": [50, 80],
        "sexo": None,
        "genetica": "Sin base genética relevante; es complicación de la diabetes de larga evolución.",
        "hallazgos": {
            "diabetes": "tipico",
            "hipoestesia_distal": "tipico",
            "parestesias_distales": "tipico",
            "arreflexia": "tipico",
            "dolor_quemazon_nocturno": "frecuente",
            "ulceras_plantares": "frecuente",
            "curso_progresivo": "tipico",
            "instauracion_semanas": "tipico",
            "artropatia_charcot": "posible",
            "neuropatia_periferica": "tipico",
            "debilidad_progresiva_asimetrica": "atipico",
            "instauracion_subita": "atipico",
            "alteracion_conciencia": "atipico",
        },
    },
    {
        "id": "encefalopatia_wernicke",
        "nombre": "Encefalopatía de Wernicke",
        "sistemas": ["neuro"],
        "edad_tipica": [40, 70],
        "sexo": "predomina_varon",
        "genetica": "Sin base genética relevante; se debe al déficit de tiamina.",
        "hallazgos": {
            "confusion": "tipico",
            "ataxia": "tipico",
            "oftalmoplejia": "tipico",
            "nistagmo": "tipico",
            "alcoholismo_cronico": "tipico",
            "diplopia": "frecuente",
            "amnesia_antegrada": "frecuente",
            "instauracion_dias": "tipico",
            "hipotension": "posible",
            "taquicardia": "posible",
            "focalidad_motora": "atipico",
            "curso_recurrente": "atipico",
            "lcr_purulento": "incompatible",
        },
    },
    {
        "id": "trombosis_venosa_cerebral",
        "nombre": "Trombosis venosa cerebral",
        "sistemas": ["neuro"],
        "edad_tipica": [20, 50],
        "sexo": "predomina_mujer",
        "genetica": "Trombofilias hereditarias: factor V Leiden, mutación de la protrombina, déficit de antitrombina III o de proteína C o S.",
        "hallazgos": {
            "cefalea_progresiva": "tipico",
            "papiledema": "tipico",
            "instauracion_dias": "tipico",
            "crisis_convulsiva": "frecuente",
            "focalidad_motora": "frecuente",
            "alteracion_conciencia": "frecuente",
            "vomitos_proyectivos": "frecuente",
            "puerperio": "posible",
            "anticoagulacion": "posible",
            "lcr_hematico": "posible",
            "lcr_proteinorraquia": "posible",
            "instauracion_subita": "atipico",
            "lcr_normal": "atipico",
        },
    },
    {
        "id": "arteritis_celulas_gigantes",
        "nombre": "Arteritis de células gigantes",
        "sistemas": ["neuro"],
        "edad_tipica": [65, 90],
        "sexo": "predomina_mujer",
        "genetica": "Asociación con HLA-DRB1*04; base poligénica inflamatoria.",
        "hallazgos": {
            "cefalea_localizada_nueva": "tipico",
            "claudicacion_mandibular": "tipico",
            "vsg_elevada": "tipico",
            "pcr_elevada": "tipico",
            "perdida_vision_unilateral": "frecuente",
            "mialgias": "frecuente",
            "artralgias": "frecuente",
            "perdida_peso": "frecuente",
            "astenia": "frecuente",
            "febricula": "frecuente",
            "instauracion_semanas": "tipico",
            "anemia": "frecuente",
            "cefalea_brusca": "atipico",
            "signos_meningeos": "atipico",
        },
    },
    {
        "id": "status_epileptico",
        "nombre": "Status epiléptico convulsivo",
        "sistemas": ["neuro"],
        "edad_tipica": [0, 90],
        "sexo": None,
        "genetica": "Depende de la causa de fondo; puede ser sintomático o criptogénico.",
        "hallazgos": {
            "crisis_convulsiva": "tipico",
            "alteracion_conciencia": "tipico",
            "instauracion_subita": "tipico",
            "antecedente_epilepsia": "frecuente",
            "taquicardia": "frecuente",
            "hipertension": "frecuente",
            "fiebre": "frecuente",
            "acidosis_metabolica": "frecuente",
            "rabdomiolisis": "posible",
            "insuficiencia_renal": "posible",
            "tc_normal": "posible",
            "instauracion_semanas": "atipico",
            "curso_progresivo": "atipico",
        },
    },
]

PATOLOGIAS_POR_ID = {p["id"]: p for p in PATOLOGIAS}

# ---------------------------------------------------------------------------
# SIGNOS PATOGNOMONICOS
# ---------------------------------------------------------------------------
# El hallazgo que, si esta, cierra el diagnostico.
#
# ESTA LISTA ES CORTA A PROPOSITO. En medicina los patognomonicos de verdad
# son rarisimos: casi todo lo que parece exclusivo de una enfermedad aparece
# tambien en otras tres. Marcar veinte seria comodo y estaria mal, y ademas
# haria justo el daño que esta app intenta evitar -enseñar un atajo falso a
# quien todavia esta aprendiendo a razonar-.
#
# Van aqui y no dentro de cada ficha porque asi se ven todos juntos y se
# puede discutir la lista entera de un vistazo, que es como hay que
# revisarla.
PATOGNOMONICOS = {
    "vppb": "dix_hallpike_positivo",
    "paralisis_supranuclear_progresiva": "oftalmoplejia_supranuclear",
    "demencia_cuerpos_lewy": "sensibilidad_neurolepticos",
    "mielofibrosis_primaria": "dacriocitos",
    "leucemia_mieloide_cronica": "basofilia",
    "macroglobulinemia_waldenstrom": "hiperviscosidad",
    "arteritis_celulas_gigantes": "claudicacion_mandibular",
    "guillain_barre": "lcr_albuminocitologica",
}

for _pid, _hid in PATOGNOMONICOS.items():
    _p = PATOLOGIAS_POR_ID.get(_pid)
    if _p and _hid in _p.get("hallazgos", {}):
        _p["hallazgos"][_hid] = "patognomonico"
